### ISSUE TITLE
发现build时的一个问题，求解决方案

### ISSUE THREAD

**Issue by ihatake** [foolishchow/vitepress-live-demo#1]
你好，我在使用该插件后，执行`npm run docs:build`打包出来的文件，iframe模式访问404，但是dev模式正常
文件目录为：
├── components
│   ├── example
│   │   ├── LoginExample.vue
│   │   └── common
│   └── login.md
├── index.md
查看源代码可能问题在于DemoBuildPlugin-generateBundle钩子中
`chunkMap![chunk.name.toLowerCase()] = hash`将name转成了小写，但是writeDemoHtml方法中没有一样转成小写
```
live_demo_chunks.forEach(chunk => {
    hash[chunk.name.replace('live_demo_', '')] = demoMap[chunk.name]
  })
```
辛苦大神看看~

**Comment by foolishchow** [comment]
的确是有问题，我也不记得当时为啥要转小写了，先去掉吧 ， 你可以试试 0.0.7
